// quiz/src/App.vue
<script setup lang="ts">
  import CustomButton from "./components/CustomButton/CustomButton.vue";
import Enunciation from "./components/Enunciation/Enunciation.vue";
</script>

<template>
  <CustomButton 
    title="Tab 1" 
    :selected="false"
    :onClick="() => {}"
  />
  <Enunciation text="Texto 1" />
</template>

<style>
  @import './assets/base.css';
</style>

// quiz/src/App.tsx
import './App.css';
import { CustomButton } from './components/CustomButton';
import { DescriptionContainer } from './components/DescriptionContainer';
import { Enunciation } from './components/Enunciation';

function App() {
  return (
    <div className="App">
      <CustomButton title="Tab 1" onClick={() => {}} />
      <DescriptionContainer>
        <Enunciation text="Texto teste" />
      </DescriptionContainer>
    </div>
  );
}

export default App;
