// quiz/src/app/components/Enunciation/enunciation.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: 'app-enunciation',
  template: `
  <div class="description-container">
    <h2 class="enunciation-text">
      <ng-content></ng-content>
    </h2>
  </div>
  `,
  styleUrls: ['./enunciation.component.css'] 
})

export class EnunciationComponent {}

// quiz/src/components/Enunciation/Enunciation.vue
<script setup lang="ts">
    interface EnunciationProps {
        text: string;
    }

    defineProps<EnunciationProps>();

</script>


<template>
    <div class="description-container">
        <h2 class="enunciation-text">
            {{ text }}
        </h2>
    </div>
</template>

<style scoped src="./styles.css"></style>
