// quiz/src/app/components/Tab/tab.component.ts
import { Component } from "@angular/core";

interface TabListType {
    title: string;
    description: string;
}

@Component({
  selector: 'app-tab',
  templateUrl: './tab.component.html',
  styleUrls: ['./tab.component.css'] 
})

export class TabComponent {
    tabList: TabListType[]  = [
        {
            "title": "Tab 1",
            "description": "Texto 1",
        },
        {
            "title": "Tab 2",
            "description": "Texto 2",
        },
        {
            "title": "Tab 3",
            "description": "Texto 3",
        },
        {
            "title": "Tab 4",
            "description": "Texto 4",
        },
    ];
    
    currentlySelectedTab = 0;
    

    tabOnClick = (tabIndex: number) => {
        this.currentlySelectedTab = tabIndex;
    };

    isTabSelected = (tabIndex: number) => {
        if (tabIndex === this.currentlySelectedTab) {
            return true;
        }

        return false;
    };
}
<div class="tab-container">
  <app-custom-button *ngFor="let tabItem of tabList; let newIndex = index"
    [title]="tabItem.title"
    [selected]="isTabSelected(newIndex)"
    [index]="newIndex"
    (onClick)="tabOnClick(newIndex)"
  >
  </app-custom-button>

  <div class="description-container">
    <app-enunciation>
      {{ tabList[currentlySelectedTab].description }}
    </app-enunciation>
  </div>
</div>

// quiz/src/components/Tab/Tab.svelte
<script setup lang="ts">
    import CustomButton from "../CustomButton/CustomButton.svelte";
    import Enunciation from "../Enunciation/Enunciation.svelte";

    const tabList = [
        {
            "title": "Tab 1",
            "description": "Texto 1",
        },
        {
            "title": "Tab 2",
            "description": "Texto 2",
        },
        {
            "title": "Tab 3",
            "description": "Texto 3",
        },
        {
            "title": "Tab 4",
            "description": "Texto 4",
        },
    ];

    let currentlySelectedTab = 0;
    
    const tabOnClick = (tabIndex: number) => {
        currentlySelectedTab = tabIndex;
    };
</script>

<div class="tab-container">
    {#each tabList as tabItem, index (tabItem)}
        <CustomButton
            title={tabItem.title}
            selected={currentlySelectedTab === index}
            index={index}
            on:selection={e => tabOnClick(e.detail)}
        />
    {/each}

    <Enunciation text={tabList[currentlySelectedTab].description} />
</div>

<style scoped src="./styles.css"></style>
