// quiz/src/components/Input/Input.vue
<script setup lang="ts">
    interface InputProps {
        type: string;
        name: string;
        value: string;
        errorMessage?: string;
    }

    defineProps<InputProps>();
</script>

<template>
    <div>
        <input :type="type" :name="name" v-model="value" />
        <small v-if="errorMessage">{{errorMessage}}</small>
    </div>
</template>

<style scoped src="./styles.css"></style>

// quiz/src/components/Input/index.tsx
import { InputHTMLAttributes } from 'react';
import { Container, Small, StyledInput } from './styles';

interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  errorMessage?: string;
}

export const Input = ({ errorMessage, ...props }: InputProps) => {
  return (
    <Container>
      <StyledInput {...props} />
      {errorMessage && <Small>{errorMessage}</Small>}
    </Container>
  );
};
