// quiz/src/components/TextArea/TextArea.vue
<script setup lang="ts">
    interface TextAreaProps {
        name: string;
        value: string;
        errorMessage?: string;
    }

    defineProps<TextAreaProps>();
</script>

<template>
    <div>
        <textarea :name="name" v-model="value" />
        <small v-if="errorMessage">{{errorMessage}}</small>
    </div>
</template>

<style scoped src="./styles.css"></style>

// quiz/src/components/TextArea/index.tsx
import { TextareaHTMLAttributes } from 'react';
import { Container, Small, StyledTextArea } from './styles';

interface TextAreaProps extends TextareaHTMLAttributes<HTMLTextAreaElement> {
  errorMessage?: string;
}

export const TextArea = ({ errorMessage, ...props }: TextAreaProps) => {
  return (
    <Container>
      <StyledTextArea {...props} />
      {errorMessage && <Small>{errorMessage}</Small>}
    </Container>
  );
};
