// quiz/src/components/CustomButton/index.tsx
import './styles.css';

interface TabProps {
    title: string;
    selected: boolean; 
    onClick: () => void;
}

export const CustomButton = (props: TabProps) => {
    const getState = () => {
        if (props.selected) {
            return ' selected';
        }

        return '';
    };

    return (
        <button
            className={`custom-button${getState()}`}
            type="button" 
            title={props.title} 
            onClick={props.onClick}
        >
            {props.title}
        </button>
    );
}

// quiz/src/app/components/CustomButton/custom-button.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";

export interface CustomButton {
  title: string;
  selected: boolean;
  index: number;
}

@Component({
  selector: 'app-custom-button',
  templateUrl: './custom-button.component.html',
  styleUrls: ['./custom-button.component.css'] 
})

export class CustomButtonComponent {
  @Input() title!: string;
  @Input() selected!: boolean;
  @Input() index!: number;

  @Output() onClick = new EventEmitter<number>();
}
<button
    type="button"
    [class]="selected ? 'selected' : ''"
    [title]="title"
    (click)="onClick.emit(index)"
>
    {{ title }}
</button>
