// quiz/src/components/CustomButton/index.tsx
import './styles.css';

interface TabProps {
    title: string;
    selected: boolean; 
    onClick: () => void;
}

export const CustomButton = (props: TabProps) => {
    const getState = () => {
        if (props.selected) {
            return ' selected';
        }

        return '';
    };

    return (
        <button
            className={`custom-button${getState()}`}
            type="button" 
            title={props.title} 
            onClick={props.onClick}
        >
            {props.title}
        </button>
    );
}

// quiz/src/components/CustomButton/CustomButton.vue
<style scoped src="./styles.css"></style>

<script setup lang="ts">
    interface CustomButtonProps {
        title: string;
        selected: boolean;
    }

    defineProps<CustomButtonProps>()
</script>

<template>
    <button
        :class="{selected: selected}"
        type="button" 
    >
        {{ title }}
    </button>
</template>
